### ISSUE TITLE
Various bugs occur when weight exponent is set to 32

### ISSUE THREAD

**Issue by stephdan** [OSUCartography/Flox#141]
The layout usually isn't computed and flows remain straight. Sometimes flows disappear. Adding arrows makes flows disappear. Adding clipping via "Flow Distance From End Point" makes flows disappear.

**Comment by berniejenny** [comment]
Two bugs fixed: large values for distanceWeightExponent lead to overflows and the initial value for distanceWeightExponent was 10 and not he value indicated by the slider.
